//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ReaderDemo.TaraWebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NyxSoft_AMS_ServicesSoap", Namespace="http://tempuri.org/")]
    public partial class NyxSoft_AMS_Services : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoadSetupModulesOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadDaysLeft_WhereOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadUserInfo_PerUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserInformation_SaveRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserChangePassword_SaveRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteRecord_RecordIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadEmployeesTransSelection_WhereOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadSettingUserAccess_WhereOperationCompleted;
        
        private System.Threading.SendOrPostCallback DELETESettingUserAccess_WHEREOperationCompleted;
        
        private System.Threading.SendOrPostCallback SettingUserAccess_SaveRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback CountCommuterAccounts_WhereOperationCompleted;
        
        private System.Threading.SendOrPostCallback CountCommuterAccounts_TodayOperationCompleted;
        
        private System.Threading.SendOrPostCallback PassengerCounts_TodayOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadCommuterAccounts_WhereOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadCommuterAccounts_Where_JSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback CommuterAccounts_SaveRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadRFIDSetting_WhereOperationCompleted;
        
        private System.Threading.SendOrPostCallback RFIDSetting_SaveRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback ScannedAdsCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback RewardsTotalOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadStationCrownVolume_Where_JSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadRewards_Where_JSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback Rewards_SaveRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback TravelHistory_SaveRecordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NyxSoft_AMS_Services() {
            this.Url = global::ReaderDemo.Properties.Settings.Default.WADemo_TaraWebservice_NyxSoft_AMS_Services;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoadSetupModulesCompletedEventHandler LoadSetupModulesCompleted;
        
        /// <remarks/>
        public event LoadDaysLeft_WhereCompletedEventHandler LoadDaysLeft_WhereCompleted;
        
        /// <remarks/>
        public event ValidateUserCompletedEventHandler ValidateUserCompleted;
        
        /// <remarks/>
        public event LoadUserInfo_PerUserIDCompletedEventHandler LoadUserInfo_PerUserIDCompleted;
        
        /// <remarks/>
        public event UserInformation_SaveRecordCompletedEventHandler UserInformation_SaveRecordCompleted;
        
        /// <remarks/>
        public event UserChangePassword_SaveRecordCompletedEventHandler UserChangePassword_SaveRecordCompleted;
        
        /// <remarks/>
        public event GetUserStatusCompletedEventHandler GetUserStatusCompleted;
        
        /// <remarks/>
        public event SetUserStatusCompletedEventHandler SetUserStatusCompleted;
        
        /// <remarks/>
        public event DeleteRecord_RecordIDCompletedEventHandler DeleteRecord_RecordIDCompleted;
        
        /// <remarks/>
        public event LoadEmployeesTransSelection_WhereCompletedEventHandler LoadEmployeesTransSelection_WhereCompleted;
        
        /// <remarks/>
        public event LoadSettingUserAccess_WhereCompletedEventHandler LoadSettingUserAccess_WhereCompleted;
        
        /// <remarks/>
        public event DELETESettingUserAccess_WHERECompletedEventHandler DELETESettingUserAccess_WHERECompleted;
        
        /// <remarks/>
        public event SettingUserAccess_SaveRecordCompletedEventHandler SettingUserAccess_SaveRecordCompleted;
        
        /// <remarks/>
        public event CountCommuterAccounts_WhereCompletedEventHandler CountCommuterAccounts_WhereCompleted;
        
        /// <remarks/>
        public event CountCommuterAccounts_TodayCompletedEventHandler CountCommuterAccounts_TodayCompleted;
        
        /// <remarks/>
        public event PassengerCounts_TodayCompletedEventHandler PassengerCounts_TodayCompleted;
        
        /// <remarks/>
        public event LoadCommuterAccounts_WhereCompletedEventHandler LoadCommuterAccounts_WhereCompleted;
        
        /// <remarks/>
        public event LoadCommuterAccounts_Where_JSONCompletedEventHandler LoadCommuterAccounts_Where_JSONCompleted;
        
        /// <remarks/>
        public event CommuterAccounts_SaveRecordCompletedEventHandler CommuterAccounts_SaveRecordCompleted;
        
        /// <remarks/>
        public event LoadRFIDSetting_WhereCompletedEventHandler LoadRFIDSetting_WhereCompleted;
        
        /// <remarks/>
        public event RFIDSetting_SaveRecordCompletedEventHandler RFIDSetting_SaveRecordCompleted;
        
        /// <remarks/>
        public event ScannedAdsCountCompletedEventHandler ScannedAdsCountCompleted;
        
        /// <remarks/>
        public event RewardsTotalCompletedEventHandler RewardsTotalCompleted;
        
        /// <remarks/>
        public event LoadStationCrownVolume_Where_JSONCompletedEventHandler LoadStationCrownVolume_Where_JSONCompleted;
        
        /// <remarks/>
        public event LoadRewards_Where_JSONCompletedEventHandler LoadRewards_Where_JSONCompleted;
        
        /// <remarks/>
        public event Rewards_SaveRecordCompletedEventHandler Rewards_SaveRecordCompleted;
        
        /// <remarks/>
        public event TravelHistory_SaveRecordCompletedEventHandler TravelHistory_SaveRecordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadSetupModules", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LoadSetupModules(string _strSetupName, string _strAccessName, string _strLicenseKey, out string _strOutput) {
            object[] results = this.Invoke("LoadSetupModules", new object[] {
                        _strSetupName,
                        _strAccessName,
                        _strLicenseKey});
            _strOutput = ((string)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoadSetupModulesAsync(string _strSetupName, string _strAccessName, string _strLicenseKey) {
            this.LoadSetupModulesAsync(_strSetupName, _strAccessName, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void LoadSetupModulesAsync(string _strSetupName, string _strAccessName, string _strLicenseKey, object userState) {
            if ((this.LoadSetupModulesOperationCompleted == null)) {
                this.LoadSetupModulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadSetupModulesOperationCompleted);
            }
            this.InvokeAsync("LoadSetupModules", new object[] {
                        _strSetupName,
                        _strAccessName,
                        _strLicenseKey}, this.LoadSetupModulesOperationCompleted, userState);
        }
        
        private void OnLoadSetupModulesOperationCompleted(object arg) {
            if ((this.LoadSetupModulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadSetupModulesCompleted(this, new LoadSetupModulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadDaysLeft_Where", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LoadDaysLeft_Where(string _strLicenseKey) {
            object[] results = this.Invoke("LoadDaysLeft_Where", new object[] {
                        _strLicenseKey});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LoadDaysLeft_WhereAsync(string _strLicenseKey) {
            this.LoadDaysLeft_WhereAsync(_strLicenseKey, null);
        }
        
        /// <remarks/>
        public void LoadDaysLeft_WhereAsync(string _strLicenseKey, object userState) {
            if ((this.LoadDaysLeft_WhereOperationCompleted == null)) {
                this.LoadDaysLeft_WhereOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadDaysLeft_WhereOperationCompleted);
            }
            this.InvokeAsync("LoadDaysLeft_Where", new object[] {
                        _strLicenseKey}, this.LoadDaysLeft_WhereOperationCompleted, userState);
        }
        
        private void OnLoadDaysLeft_WhereOperationCompleted(object arg) {
            if ((this.LoadDaysLeft_WhereCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadDaysLeft_WhereCompleted(this, new LoadDaysLeft_WhereCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ValidateUser(string Username, string Password, string _strLicenseKey, out string _strOutput) {
            object[] results = this.Invoke("ValidateUser", new object[] {
                        Username,
                        Password,
                        _strLicenseKey});
            _strOutput = ((string)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string Username, string Password, string _strLicenseKey) {
            this.ValidateUserAsync(Username, Password, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string Username, string Password, string _strLicenseKey, object userState) {
            if ((this.ValidateUserOperationCompleted == null)) {
                this.ValidateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserOperationCompleted);
            }
            this.InvokeAsync("ValidateUser", new object[] {
                        Username,
                        Password,
                        _strLicenseKey}, this.ValidateUserOperationCompleted, userState);
        }
        
        private void OnValidateUserOperationCompleted(object arg) {
            if ((this.ValidateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserCompleted(this, new ValidateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadUserInfo_PerUserID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LoadUserInfo_PerUserID(int _intID, string _strLicenseKey) {
            object[] results = this.Invoke("LoadUserInfo_PerUserID", new object[] {
                        _intID,
                        _strLicenseKey});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoadUserInfo_PerUserIDAsync(int _intID, string _strLicenseKey) {
            this.LoadUserInfo_PerUserIDAsync(_intID, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void LoadUserInfo_PerUserIDAsync(int _intID, string _strLicenseKey, object userState) {
            if ((this.LoadUserInfo_PerUserIDOperationCompleted == null)) {
                this.LoadUserInfo_PerUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadUserInfo_PerUserIDOperationCompleted);
            }
            this.InvokeAsync("LoadUserInfo_PerUserID", new object[] {
                        _intID,
                        _strLicenseKey}, this.LoadUserInfo_PerUserIDOperationCompleted, userState);
        }
        
        private void OnLoadUserInfo_PerUserIDOperationCompleted(object arg) {
            if ((this.LoadUserInfo_PerUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadUserInfo_PerUserIDCompleted(this, new LoadUserInfo_PerUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserInformation_SaveRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UserInformation_SaveRecord(bool _IsEdit, string _strInputValidation, string _strInputs, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] _byteInputs, string _strLicenseKey) {
            object[] results = this.Invoke("UserInformation_SaveRecord", new object[] {
                        _IsEdit,
                        _strInputValidation,
                        _strInputs,
                        _byteInputs,
                        _strLicenseKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UserInformation_SaveRecordAsync(bool _IsEdit, string _strInputValidation, string _strInputs, byte[] _byteInputs, string _strLicenseKey) {
            this.UserInformation_SaveRecordAsync(_IsEdit, _strInputValidation, _strInputs, _byteInputs, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void UserInformation_SaveRecordAsync(bool _IsEdit, string _strInputValidation, string _strInputs, byte[] _byteInputs, string _strLicenseKey, object userState) {
            if ((this.UserInformation_SaveRecordOperationCompleted == null)) {
                this.UserInformation_SaveRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserInformation_SaveRecordOperationCompleted);
            }
            this.InvokeAsync("UserInformation_SaveRecord", new object[] {
                        _IsEdit,
                        _strInputValidation,
                        _strInputs,
                        _byteInputs,
                        _strLicenseKey}, this.UserInformation_SaveRecordOperationCompleted, userState);
        }
        
        private void OnUserInformation_SaveRecordOperationCompleted(object arg) {
            if ((this.UserInformation_SaveRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserInformation_SaveRecordCompleted(this, new UserInformation_SaveRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserChangePassword_SaveRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UserChangePassword_SaveRecord(bool _IsEdit, string _strInputValidation, string _strInputs, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] _byteInputs, string _strLicenseKey) {
            object[] results = this.Invoke("UserChangePassword_SaveRecord", new object[] {
                        _IsEdit,
                        _strInputValidation,
                        _strInputs,
                        _byteInputs,
                        _strLicenseKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UserChangePassword_SaveRecordAsync(bool _IsEdit, string _strInputValidation, string _strInputs, byte[] _byteInputs, string _strLicenseKey) {
            this.UserChangePassword_SaveRecordAsync(_IsEdit, _strInputValidation, _strInputs, _byteInputs, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void UserChangePassword_SaveRecordAsync(bool _IsEdit, string _strInputValidation, string _strInputs, byte[] _byteInputs, string _strLicenseKey, object userState) {
            if ((this.UserChangePassword_SaveRecordOperationCompleted == null)) {
                this.UserChangePassword_SaveRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserChangePassword_SaveRecordOperationCompleted);
            }
            this.InvokeAsync("UserChangePassword_SaveRecord", new object[] {
                        _IsEdit,
                        _strInputValidation,
                        _strInputs,
                        _byteInputs,
                        _strLicenseKey}, this.UserChangePassword_SaveRecordOperationCompleted, userState);
        }
        
        private void OnUserChangePassword_SaveRecordOperationCompleted(object arg) {
            if ((this.UserChangePassword_SaveRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserChangePassword_SaveRecordCompleted(this, new UserChangePassword_SaveRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetUserStatus(string _strUserID, string _strLicenseKey) {
            object[] results = this.Invoke("GetUserStatus", new object[] {
                        _strUserID,
                        _strLicenseKey});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserStatusAsync(string _strUserID, string _strLicenseKey) {
            this.GetUserStatusAsync(_strUserID, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void GetUserStatusAsync(string _strUserID, string _strLicenseKey, object userState) {
            if ((this.GetUserStatusOperationCompleted == null)) {
                this.GetUserStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserStatusOperationCompleted);
            }
            this.InvokeAsync("GetUserStatus", new object[] {
                        _strUserID,
                        _strLicenseKey}, this.GetUserStatusOperationCompleted, userState);
        }
        
        private void OnGetUserStatusOperationCompleted(object arg) {
            if ((this.GetUserStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserStatusCompleted(this, new GetUserStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetUserStatus(string _strCustomerID, string _strStatus, string _strUserID, string _strLicenseKey) {
            object[] results = this.Invoke("SetUserStatus", new object[] {
                        _strCustomerID,
                        _strStatus,
                        _strUserID,
                        _strLicenseKey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetUserStatusAsync(string _strCustomerID, string _strStatus, string _strUserID, string _strLicenseKey) {
            this.SetUserStatusAsync(_strCustomerID, _strStatus, _strUserID, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void SetUserStatusAsync(string _strCustomerID, string _strStatus, string _strUserID, string _strLicenseKey, object userState) {
            if ((this.SetUserStatusOperationCompleted == null)) {
                this.SetUserStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserStatusOperationCompleted);
            }
            this.InvokeAsync("SetUserStatus", new object[] {
                        _strCustomerID,
                        _strStatus,
                        _strUserID,
                        _strLicenseKey}, this.SetUserStatusOperationCompleted, userState);
        }
        
        private void OnSetUserStatusOperationCompleted(object arg) {
            if ((this.SetUserStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserStatusCompleted(this, new SetUserStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteRecord_RecordID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteRecord_RecordID(string _intID, string _strTableName, string _strLicenseKey) {
            object[] results = this.Invoke("DeleteRecord_RecordID", new object[] {
                        _intID,
                        _strTableName,
                        _strLicenseKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteRecord_RecordIDAsync(string _intID, string _strTableName, string _strLicenseKey) {
            this.DeleteRecord_RecordIDAsync(_intID, _strTableName, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void DeleteRecord_RecordIDAsync(string _intID, string _strTableName, string _strLicenseKey, object userState) {
            if ((this.DeleteRecord_RecordIDOperationCompleted == null)) {
                this.DeleteRecord_RecordIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteRecord_RecordIDOperationCompleted);
            }
            this.InvokeAsync("DeleteRecord_RecordID", new object[] {
                        _intID,
                        _strTableName,
                        _strLicenseKey}, this.DeleteRecord_RecordIDOperationCompleted, userState);
        }
        
        private void OnDeleteRecord_RecordIDOperationCompleted(object arg) {
            if ((this.DeleteRecord_RecordIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteRecord_RecordIDCompleted(this, new DeleteRecord_RecordIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadEmployeesTransSelection_Where", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LoadEmployeesTransSelection_Where(string _strModuleName, string _strLicenseKey) {
            object[] results = this.Invoke("LoadEmployeesTransSelection_Where", new object[] {
                        _strModuleName,
                        _strLicenseKey});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoadEmployeesTransSelection_WhereAsync(string _strModuleName, string _strLicenseKey) {
            this.LoadEmployeesTransSelection_WhereAsync(_strModuleName, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void LoadEmployeesTransSelection_WhereAsync(string _strModuleName, string _strLicenseKey, object userState) {
            if ((this.LoadEmployeesTransSelection_WhereOperationCompleted == null)) {
                this.LoadEmployeesTransSelection_WhereOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadEmployeesTransSelection_WhereOperationCompleted);
            }
            this.InvokeAsync("LoadEmployeesTransSelection_Where", new object[] {
                        _strModuleName,
                        _strLicenseKey}, this.LoadEmployeesTransSelection_WhereOperationCompleted, userState);
        }
        
        private void OnLoadEmployeesTransSelection_WhereOperationCompleted(object arg) {
            if ((this.LoadEmployeesTransSelection_WhereCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadEmployeesTransSelection_WhereCompleted(this, new LoadEmployeesTransSelection_WhereCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadSettingUserAccess_Where", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LoadSettingUserAccess_Where(string _strInputWhereStatement, string _strLicenseKey) {
            object[] results = this.Invoke("LoadSettingUserAccess_Where", new object[] {
                        _strInputWhereStatement,
                        _strLicenseKey});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoadSettingUserAccess_WhereAsync(string _strInputWhereStatement, string _strLicenseKey) {
            this.LoadSettingUserAccess_WhereAsync(_strInputWhereStatement, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void LoadSettingUserAccess_WhereAsync(string _strInputWhereStatement, string _strLicenseKey, object userState) {
            if ((this.LoadSettingUserAccess_WhereOperationCompleted == null)) {
                this.LoadSettingUserAccess_WhereOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadSettingUserAccess_WhereOperationCompleted);
            }
            this.InvokeAsync("LoadSettingUserAccess_Where", new object[] {
                        _strInputWhereStatement,
                        _strLicenseKey}, this.LoadSettingUserAccess_WhereOperationCompleted, userState);
        }
        
        private void OnLoadSettingUserAccess_WhereOperationCompleted(object arg) {
            if ((this.LoadSettingUserAccess_WhereCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadSettingUserAccess_WhereCompleted(this, new LoadSettingUserAccess_WhereCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DELETESettingUserAccess_WHERE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DELETESettingUserAccess_WHERE(string _strAccessname, string _strLicenseKey) {
            object[] results = this.Invoke("DELETESettingUserAccess_WHERE", new object[] {
                        _strAccessname,
                        _strLicenseKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DELETESettingUserAccess_WHEREAsync(string _strAccessname, string _strLicenseKey) {
            this.DELETESettingUserAccess_WHEREAsync(_strAccessname, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void DELETESettingUserAccess_WHEREAsync(string _strAccessname, string _strLicenseKey, object userState) {
            if ((this.DELETESettingUserAccess_WHEREOperationCompleted == null)) {
                this.DELETESettingUserAccess_WHEREOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDELETESettingUserAccess_WHEREOperationCompleted);
            }
            this.InvokeAsync("DELETESettingUserAccess_WHERE", new object[] {
                        _strAccessname,
                        _strLicenseKey}, this.DELETESettingUserAccess_WHEREOperationCompleted, userState);
        }
        
        private void OnDELETESettingUserAccess_WHEREOperationCompleted(object arg) {
            if ((this.DELETESettingUserAccess_WHERECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DELETESettingUserAccess_WHERECompleted(this, new DELETESettingUserAccess_WHERECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SettingUserAccess_SaveRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SettingUserAccess_SaveRecord(bool _IsEdit, string _strInputValidation, string _strInputs, string _strLicenseKey) {
            object[] results = this.Invoke("SettingUserAccess_SaveRecord", new object[] {
                        _IsEdit,
                        _strInputValidation,
                        _strInputs,
                        _strLicenseKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SettingUserAccess_SaveRecordAsync(bool _IsEdit, string _strInputValidation, string _strInputs, string _strLicenseKey) {
            this.SettingUserAccess_SaveRecordAsync(_IsEdit, _strInputValidation, _strInputs, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void SettingUserAccess_SaveRecordAsync(bool _IsEdit, string _strInputValidation, string _strInputs, string _strLicenseKey, object userState) {
            if ((this.SettingUserAccess_SaveRecordOperationCompleted == null)) {
                this.SettingUserAccess_SaveRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSettingUserAccess_SaveRecordOperationCompleted);
            }
            this.InvokeAsync("SettingUserAccess_SaveRecord", new object[] {
                        _IsEdit,
                        _strInputValidation,
                        _strInputs,
                        _strLicenseKey}, this.SettingUserAccess_SaveRecordOperationCompleted, userState);
        }
        
        private void OnSettingUserAccess_SaveRecordOperationCompleted(object arg) {
            if ((this.SettingUserAccess_SaveRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SettingUserAccess_SaveRecordCompleted(this, new SettingUserAccess_SaveRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CountCommuterAccounts_Where", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long CountCommuterAccounts_Where(string _strLicenseKey) {
            object[] results = this.Invoke("CountCommuterAccounts_Where", new object[] {
                        _strLicenseKey});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void CountCommuterAccounts_WhereAsync(string _strLicenseKey) {
            this.CountCommuterAccounts_WhereAsync(_strLicenseKey, null);
        }
        
        /// <remarks/>
        public void CountCommuterAccounts_WhereAsync(string _strLicenseKey, object userState) {
            if ((this.CountCommuterAccounts_WhereOperationCompleted == null)) {
                this.CountCommuterAccounts_WhereOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCountCommuterAccounts_WhereOperationCompleted);
            }
            this.InvokeAsync("CountCommuterAccounts_Where", new object[] {
                        _strLicenseKey}, this.CountCommuterAccounts_WhereOperationCompleted, userState);
        }
        
        private void OnCountCommuterAccounts_WhereOperationCompleted(object arg) {
            if ((this.CountCommuterAccounts_WhereCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CountCommuterAccounts_WhereCompleted(this, new CountCommuterAccounts_WhereCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CountCommuterAccounts_Today", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long CountCommuterAccounts_Today(string _strLicenseKey) {
            object[] results = this.Invoke("CountCommuterAccounts_Today", new object[] {
                        _strLicenseKey});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void CountCommuterAccounts_TodayAsync(string _strLicenseKey) {
            this.CountCommuterAccounts_TodayAsync(_strLicenseKey, null);
        }
        
        /// <remarks/>
        public void CountCommuterAccounts_TodayAsync(string _strLicenseKey, object userState) {
            if ((this.CountCommuterAccounts_TodayOperationCompleted == null)) {
                this.CountCommuterAccounts_TodayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCountCommuterAccounts_TodayOperationCompleted);
            }
            this.InvokeAsync("CountCommuterAccounts_Today", new object[] {
                        _strLicenseKey}, this.CountCommuterAccounts_TodayOperationCompleted, userState);
        }
        
        private void OnCountCommuterAccounts_TodayOperationCompleted(object arg) {
            if ((this.CountCommuterAccounts_TodayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CountCommuterAccounts_TodayCompleted(this, new CountCommuterAccounts_TodayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PassengerCounts_Today", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long PassengerCounts_Today(string _strLicenseKey) {
            object[] results = this.Invoke("PassengerCounts_Today", new object[] {
                        _strLicenseKey});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void PassengerCounts_TodayAsync(string _strLicenseKey) {
            this.PassengerCounts_TodayAsync(_strLicenseKey, null);
        }
        
        /// <remarks/>
        public void PassengerCounts_TodayAsync(string _strLicenseKey, object userState) {
            if ((this.PassengerCounts_TodayOperationCompleted == null)) {
                this.PassengerCounts_TodayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPassengerCounts_TodayOperationCompleted);
            }
            this.InvokeAsync("PassengerCounts_Today", new object[] {
                        _strLicenseKey}, this.PassengerCounts_TodayOperationCompleted, userState);
        }
        
        private void OnPassengerCounts_TodayOperationCompleted(object arg) {
            if ((this.PassengerCounts_TodayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PassengerCounts_TodayCompleted(this, new PassengerCounts_TodayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadCommuterAccounts_Where", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LoadCommuterAccounts_Where(string _strInputWhereStatement, string _strLicenseKey) {
            object[] results = this.Invoke("LoadCommuterAccounts_Where", new object[] {
                        _strInputWhereStatement,
                        _strLicenseKey});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoadCommuterAccounts_WhereAsync(string _strInputWhereStatement, string _strLicenseKey) {
            this.LoadCommuterAccounts_WhereAsync(_strInputWhereStatement, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void LoadCommuterAccounts_WhereAsync(string _strInputWhereStatement, string _strLicenseKey, object userState) {
            if ((this.LoadCommuterAccounts_WhereOperationCompleted == null)) {
                this.LoadCommuterAccounts_WhereOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadCommuterAccounts_WhereOperationCompleted);
            }
            this.InvokeAsync("LoadCommuterAccounts_Where", new object[] {
                        _strInputWhereStatement,
                        _strLicenseKey}, this.LoadCommuterAccounts_WhereOperationCompleted, userState);
        }
        
        private void OnLoadCommuterAccounts_WhereOperationCompleted(object arg) {
            if ((this.LoadCommuterAccounts_WhereCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadCommuterAccounts_WhereCompleted(this, new LoadCommuterAccounts_WhereCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadCommuterAccounts_Where_JSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LoadCommuterAccounts_Where_JSON(string _strInputWhereStatement, string _strLicenseKey) {
            this.Invoke("LoadCommuterAccounts_Where_JSON", new object[] {
                        _strInputWhereStatement,
                        _strLicenseKey});
        }
        
        /// <remarks/>
        public void LoadCommuterAccounts_Where_JSONAsync(string _strInputWhereStatement, string _strLicenseKey) {
            this.LoadCommuterAccounts_Where_JSONAsync(_strInputWhereStatement, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void LoadCommuterAccounts_Where_JSONAsync(string _strInputWhereStatement, string _strLicenseKey, object userState) {
            if ((this.LoadCommuterAccounts_Where_JSONOperationCompleted == null)) {
                this.LoadCommuterAccounts_Where_JSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadCommuterAccounts_Where_JSONOperationCompleted);
            }
            this.InvokeAsync("LoadCommuterAccounts_Where_JSON", new object[] {
                        _strInputWhereStatement,
                        _strLicenseKey}, this.LoadCommuterAccounts_Where_JSONOperationCompleted, userState);
        }
        
        private void OnLoadCommuterAccounts_Where_JSONOperationCompleted(object arg) {
            if ((this.LoadCommuterAccounts_Where_JSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadCommuterAccounts_Where_JSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CommuterAccounts_SaveRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CommuterAccounts_SaveRecord(bool _IsEdit, string _strInputs, string _strLicenseKey) {
            object[] results = this.Invoke("CommuterAccounts_SaveRecord", new object[] {
                        _IsEdit,
                        _strInputs,
                        _strLicenseKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CommuterAccounts_SaveRecordAsync(bool _IsEdit, string _strInputs, string _strLicenseKey) {
            this.CommuterAccounts_SaveRecordAsync(_IsEdit, _strInputs, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void CommuterAccounts_SaveRecordAsync(bool _IsEdit, string _strInputs, string _strLicenseKey, object userState) {
            if ((this.CommuterAccounts_SaveRecordOperationCompleted == null)) {
                this.CommuterAccounts_SaveRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommuterAccounts_SaveRecordOperationCompleted);
            }
            this.InvokeAsync("CommuterAccounts_SaveRecord", new object[] {
                        _IsEdit,
                        _strInputs,
                        _strLicenseKey}, this.CommuterAccounts_SaveRecordOperationCompleted, userState);
        }
        
        private void OnCommuterAccounts_SaveRecordOperationCompleted(object arg) {
            if ((this.CommuterAccounts_SaveRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CommuterAccounts_SaveRecordCompleted(this, new CommuterAccounts_SaveRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadRFIDSetting_Where", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LoadRFIDSetting_Where(string _strInputWhereStatement, string _strLicenseKey) {
            object[] results = this.Invoke("LoadRFIDSetting_Where", new object[] {
                        _strInputWhereStatement,
                        _strLicenseKey});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoadRFIDSetting_WhereAsync(string _strInputWhereStatement, string _strLicenseKey) {
            this.LoadRFIDSetting_WhereAsync(_strInputWhereStatement, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void LoadRFIDSetting_WhereAsync(string _strInputWhereStatement, string _strLicenseKey, object userState) {
            if ((this.LoadRFIDSetting_WhereOperationCompleted == null)) {
                this.LoadRFIDSetting_WhereOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadRFIDSetting_WhereOperationCompleted);
            }
            this.InvokeAsync("LoadRFIDSetting_Where", new object[] {
                        _strInputWhereStatement,
                        _strLicenseKey}, this.LoadRFIDSetting_WhereOperationCompleted, userState);
        }
        
        private void OnLoadRFIDSetting_WhereOperationCompleted(object arg) {
            if ((this.LoadRFIDSetting_WhereCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadRFIDSetting_WhereCompleted(this, new LoadRFIDSetting_WhereCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RFIDSetting_SaveRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RFIDSetting_SaveRecord(string _strInputs, string _strLicenseKey) {
            object[] results = this.Invoke("RFIDSetting_SaveRecord", new object[] {
                        _strInputs,
                        _strLicenseKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RFIDSetting_SaveRecordAsync(string _strInputs, string _strLicenseKey) {
            this.RFIDSetting_SaveRecordAsync(_strInputs, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void RFIDSetting_SaveRecordAsync(string _strInputs, string _strLicenseKey, object userState) {
            if ((this.RFIDSetting_SaveRecordOperationCompleted == null)) {
                this.RFIDSetting_SaveRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRFIDSetting_SaveRecordOperationCompleted);
            }
            this.InvokeAsync("RFIDSetting_SaveRecord", new object[] {
                        _strInputs,
                        _strLicenseKey}, this.RFIDSetting_SaveRecordOperationCompleted, userState);
        }
        
        private void OnRFIDSetting_SaveRecordOperationCompleted(object arg) {
            if ((this.RFIDSetting_SaveRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RFIDSetting_SaveRecordCompleted(this, new RFIDSetting_SaveRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannedAdsCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ScannedAdsCount(string _strLicenseKey) {
            object[] results = this.Invoke("ScannedAdsCount", new object[] {
                        _strLicenseKey});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void ScannedAdsCountAsync(string _strLicenseKey) {
            this.ScannedAdsCountAsync(_strLicenseKey, null);
        }
        
        /// <remarks/>
        public void ScannedAdsCountAsync(string _strLicenseKey, object userState) {
            if ((this.ScannedAdsCountOperationCompleted == null)) {
                this.ScannedAdsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnScannedAdsCountOperationCompleted);
            }
            this.InvokeAsync("ScannedAdsCount", new object[] {
                        _strLicenseKey}, this.ScannedAdsCountOperationCompleted, userState);
        }
        
        private void OnScannedAdsCountOperationCompleted(object arg) {
            if ((this.ScannedAdsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ScannedAdsCountCompleted(this, new ScannedAdsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RewardsTotal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal RewardsTotal(string _strLicenseKey) {
            object[] results = this.Invoke("RewardsTotal", new object[] {
                        _strLicenseKey});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void RewardsTotalAsync(string _strLicenseKey) {
            this.RewardsTotalAsync(_strLicenseKey, null);
        }
        
        /// <remarks/>
        public void RewardsTotalAsync(string _strLicenseKey, object userState) {
            if ((this.RewardsTotalOperationCompleted == null)) {
                this.RewardsTotalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRewardsTotalOperationCompleted);
            }
            this.InvokeAsync("RewardsTotal", new object[] {
                        _strLicenseKey}, this.RewardsTotalOperationCompleted, userState);
        }
        
        private void OnRewardsTotalOperationCompleted(object arg) {
            if ((this.RewardsTotalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RewardsTotalCompleted(this, new RewardsTotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadStationCrownVolume_Where_JSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LoadStationCrownVolume_Where_JSON(string _strInputWhereStatement, string _strLicenseKey) {
            this.Invoke("LoadStationCrownVolume_Where_JSON", new object[] {
                        _strInputWhereStatement,
                        _strLicenseKey});
        }
        
        /// <remarks/>
        public void LoadStationCrownVolume_Where_JSONAsync(string _strInputWhereStatement, string _strLicenseKey) {
            this.LoadStationCrownVolume_Where_JSONAsync(_strInputWhereStatement, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void LoadStationCrownVolume_Where_JSONAsync(string _strInputWhereStatement, string _strLicenseKey, object userState) {
            if ((this.LoadStationCrownVolume_Where_JSONOperationCompleted == null)) {
                this.LoadStationCrownVolume_Where_JSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadStationCrownVolume_Where_JSONOperationCompleted);
            }
            this.InvokeAsync("LoadStationCrownVolume_Where_JSON", new object[] {
                        _strInputWhereStatement,
                        _strLicenseKey}, this.LoadStationCrownVolume_Where_JSONOperationCompleted, userState);
        }
        
        private void OnLoadStationCrownVolume_Where_JSONOperationCompleted(object arg) {
            if ((this.LoadStationCrownVolume_Where_JSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadStationCrownVolume_Where_JSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadRewards_Where_JSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LoadRewards_Where_JSON(string _strInputWhereStatement, string _strLicenseKey) {
            this.Invoke("LoadRewards_Where_JSON", new object[] {
                        _strInputWhereStatement,
                        _strLicenseKey});
        }
        
        /// <remarks/>
        public void LoadRewards_Where_JSONAsync(string _strInputWhereStatement, string _strLicenseKey) {
            this.LoadRewards_Where_JSONAsync(_strInputWhereStatement, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void LoadRewards_Where_JSONAsync(string _strInputWhereStatement, string _strLicenseKey, object userState) {
            if ((this.LoadRewards_Where_JSONOperationCompleted == null)) {
                this.LoadRewards_Where_JSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadRewards_Where_JSONOperationCompleted);
            }
            this.InvokeAsync("LoadRewards_Where_JSON", new object[] {
                        _strInputWhereStatement,
                        _strLicenseKey}, this.LoadRewards_Where_JSONOperationCompleted, userState);
        }
        
        private void OnLoadRewards_Where_JSONOperationCompleted(object arg) {
            if ((this.LoadRewards_Where_JSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadRewards_Where_JSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Rewards_SaveRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Rewards_SaveRecord(string _strInputs, string _strLicenseKey) {
            object[] results = this.Invoke("Rewards_SaveRecord", new object[] {
                        _strInputs,
                        _strLicenseKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Rewards_SaveRecordAsync(string _strInputs, string _strLicenseKey) {
            this.Rewards_SaveRecordAsync(_strInputs, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void Rewards_SaveRecordAsync(string _strInputs, string _strLicenseKey, object userState) {
            if ((this.Rewards_SaveRecordOperationCompleted == null)) {
                this.Rewards_SaveRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRewards_SaveRecordOperationCompleted);
            }
            this.InvokeAsync("Rewards_SaveRecord", new object[] {
                        _strInputs,
                        _strLicenseKey}, this.Rewards_SaveRecordOperationCompleted, userState);
        }
        
        private void OnRewards_SaveRecordOperationCompleted(object arg) {
            if ((this.Rewards_SaveRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Rewards_SaveRecordCompleted(this, new Rewards_SaveRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TravelHistory_SaveRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TravelHistory_SaveRecord(string[] _strInputArray, string _strLicenseKey) {
            object[] results = this.Invoke("TravelHistory_SaveRecord", new object[] {
                        _strInputArray,
                        _strLicenseKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TravelHistory_SaveRecordAsync(string[] _strInputArray, string _strLicenseKey) {
            this.TravelHistory_SaveRecordAsync(_strInputArray, _strLicenseKey, null);
        }
        
        /// <remarks/>
        public void TravelHistory_SaveRecordAsync(string[] _strInputArray, string _strLicenseKey, object userState) {
            if ((this.TravelHistory_SaveRecordOperationCompleted == null)) {
                this.TravelHistory_SaveRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTravelHistory_SaveRecordOperationCompleted);
            }
            this.InvokeAsync("TravelHistory_SaveRecord", new object[] {
                        _strInputArray,
                        _strLicenseKey}, this.TravelHistory_SaveRecordOperationCompleted, userState);
        }
        
        private void OnTravelHistory_SaveRecordOperationCompleted(object arg) {
            if ((this.TravelHistory_SaveRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TravelHistory_SaveRecordCompleted(this, new TravelHistory_SaveRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LoadSetupModulesCompletedEventHandler(object sender, LoadSetupModulesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadSetupModulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadSetupModulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string _strOutput {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LoadDaysLeft_WhereCompletedEventHandler(object sender, LoadDaysLeft_WhereCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadDaysLeft_WhereCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadDaysLeft_WhereCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ValidateUserCompletedEventHandler(object sender, ValidateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string _strOutput {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LoadUserInfo_PerUserIDCompletedEventHandler(object sender, LoadUserInfo_PerUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadUserInfo_PerUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadUserInfo_PerUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UserInformation_SaveRecordCompletedEventHandler(object sender, UserInformation_SaveRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserInformation_SaveRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserInformation_SaveRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UserChangePassword_SaveRecordCompletedEventHandler(object sender, UserChangePassword_SaveRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserChangePassword_SaveRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserChangePassword_SaveRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetUserStatusCompletedEventHandler(object sender, GetUserStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SetUserStatusCompletedEventHandler(object sender, SetUserStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetUserStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetUserStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteRecord_RecordIDCompletedEventHandler(object sender, DeleteRecord_RecordIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteRecord_RecordIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteRecord_RecordIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LoadEmployeesTransSelection_WhereCompletedEventHandler(object sender, LoadEmployeesTransSelection_WhereCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadEmployeesTransSelection_WhereCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadEmployeesTransSelection_WhereCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LoadSettingUserAccess_WhereCompletedEventHandler(object sender, LoadSettingUserAccess_WhereCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadSettingUserAccess_WhereCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadSettingUserAccess_WhereCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DELETESettingUserAccess_WHERECompletedEventHandler(object sender, DELETESettingUserAccess_WHERECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DELETESettingUserAccess_WHERECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DELETESettingUserAccess_WHERECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SettingUserAccess_SaveRecordCompletedEventHandler(object sender, SettingUserAccess_SaveRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SettingUserAccess_SaveRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SettingUserAccess_SaveRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CountCommuterAccounts_WhereCompletedEventHandler(object sender, CountCommuterAccounts_WhereCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountCommuterAccounts_WhereCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CountCommuterAccounts_WhereCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CountCommuterAccounts_TodayCompletedEventHandler(object sender, CountCommuterAccounts_TodayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountCommuterAccounts_TodayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CountCommuterAccounts_TodayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void PassengerCounts_TodayCompletedEventHandler(object sender, PassengerCounts_TodayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PassengerCounts_TodayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PassengerCounts_TodayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LoadCommuterAccounts_WhereCompletedEventHandler(object sender, LoadCommuterAccounts_WhereCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadCommuterAccounts_WhereCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadCommuterAccounts_WhereCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LoadCommuterAccounts_Where_JSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CommuterAccounts_SaveRecordCompletedEventHandler(object sender, CommuterAccounts_SaveRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CommuterAccounts_SaveRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CommuterAccounts_SaveRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LoadRFIDSetting_WhereCompletedEventHandler(object sender, LoadRFIDSetting_WhereCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadRFIDSetting_WhereCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadRFIDSetting_WhereCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RFIDSetting_SaveRecordCompletedEventHandler(object sender, RFIDSetting_SaveRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RFIDSetting_SaveRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RFIDSetting_SaveRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ScannedAdsCountCompletedEventHandler(object sender, ScannedAdsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ScannedAdsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ScannedAdsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RewardsTotalCompletedEventHandler(object sender, RewardsTotalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RewardsTotalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RewardsTotalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LoadStationCrownVolume_Where_JSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LoadRewards_Where_JSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void Rewards_SaveRecordCompletedEventHandler(object sender, Rewards_SaveRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rewards_SaveRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Rewards_SaveRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void TravelHistory_SaveRecordCompletedEventHandler(object sender, TravelHistory_SaveRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TravelHistory_SaveRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TravelHistory_SaveRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591